In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

In [4]:
A = matriz * vector

In [5]:
print(A)

[[ 2  6]
 [ 6 12]
 [10 18]]


In [6]:
B = matriz.dot(vector)

In [7]:
print(B)

[ 8 18 28]


Cuando hacemos una matriz por vector nos da una matriz de 3x2

<img src ="Imagenes\1.jpg">

Para el producto de DOT ver imagen 2

<img src ="Imagenes\2.JPG">

In [10]:
B = matriz.dot(vector)
C = np.dot(matriz,vector)

print(B)
print(C)

[ 8 18 28]
[ 8 18 28]


In [11]:
matriz1 = np.array([[1,2,3],[3,4,5]])
tensor = np.array([
    [[1,2],[3,4],[5,6]],
    [[1,2],[3,4],[5,6]],
    [[1,2],[3,4],[5,6]]
])
D = np.dot(matriz1 , tensor)
E = np.dot(tensor , matriz1)
F = np.dot(matriz1 , matriz1.T)
G = np.dot(matriz1.T, matriz1)
print('D:')
print(D)
print('E:')
print(E)
print('F:')
print(F)
print('G:')
print(G)

D:
[[[22 28]
  [22 28]
  [22 28]]

 [[40 52]
  [40 52]
  [40 52]]]
E:
[[[ 7 10 13]
  [15 22 29]
  [23 34 45]]

 [[ 7 10 13]
  [15 22 29]
  [23 34 45]]

 [[ 7 10 13]
  [15 22 29]
  [23 34 45]]]
F:
[[14 26]
 [26 50]]
G:
[[10 14 18]
 [14 20 26]
 [18 26 34]]


In [12]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b = np.array([[1, 2], [3, 4], [5, 6]])
print(a.shape)

(4, 3)


In [13]:
print(b.shape)

(3, 2)


In [16]:
C = a.dot(b)
C

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136]])

In [18]:
D = b.dot(a)  #Los numeros que tienen en cada matriz la dimension 1 debe ser igual a la dimension 0 de la otra matriz

ValueError: shapes (3,2) and (4,3) not aligned: 2 (dim 1) != 4 (dim 0)

## Propiedades de las matrices: la multiplicación de matrices es asociativa y distributiva, no es conmutativa

In [21]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])

### Asociativa

In [22]:
ABC = A.dot(B.dot(C))
print(ABC)

[[ 60  26]
 [145  63]
 [295 129]]


In [24]:
AB_C = A.dot(B).dot(C)
print(AB_C)

[[ 60  26]
 [145  63]
 [295 129]]


### Distributiva

In [25]:
D = A.dot(B+C)
E = (A.dot(B)) + (A.dot(C))

In [26]:
print(D)
print(E)

[[ 26  17]
 [ 62  41]
 [122  83]]
[[ 26  17]
 [ 62  41]
 [122  83]]


In [29]:
B / C

array([[0.33333333, 3.        ],
       [0.5       , 0.5       ]])

### Conmutativa

In [30]:
F= B.dot(C)
G = C.dot(B)

In [31]:
print(F)
print(G)

[[15  7]
 [10  4]]
[[ 5 10]
 [ 8 14]]


In [32]:
print(F == G)

[[False False]
 [False False]]


#### En matrices no es conmutativa pero en vectores si

In [35]:
v1 = np.array([[2],[3]])
v2 = np.array([[0],[5]])

In [37]:
v1_tv2 = v1.T.dot(v2)
v2_tv1 = v2.T.dot(v1)

In [38]:
print(v1_tv2)
print(v2_tv1)

[[15]]
[[15]]
